language: java
jdk:
- oraclejdk8
script: mvn clean verify
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: InyQwoXppC2/a5YrC+PnMJA/Agltf4QqIojkKsFL/+CRaV5B4zdKfiBQ0C27jDjLJ1ithX0vZddSAGqT23TwsfSm6e9yKAqoZL3x7civgLsADnGs7rmsmLMS/QeebNGb2WeEUiNx/lNKmNFaStCpGpWggLfDwNAA/DEnP0nebMxGdPD/C1bNEODGXR2FEHmz7mVW80uVArKYUneFmPTt1NNnL3N2VoPMnCGQ3ghaJR8utPB4vXbQqjEvxY4dRAjCNvKrmkrD6XUCI+D8WndwRvnweUh1BmNHdQz8trWT9HYwiB5rYd/AuKk2fffhBQ4uKLJQFmD9U3aLTtZhZ9+4Ep1SDNoupFFHF45/G9n4/wdxlBboZczlpGWbLO7K6Xhz6pYHgmzpXYZuJOQQgo6kYU91iXw8gpfPktNRYFfzTQ0uNajxWlKZC3/J7PfIty4lC/PdVF9NSuO7rzk1e9a7wWLzoiQBCRzj9RFpl4x70fCbKPYzSWdmDEkfvyk5m4agMxchIA8WP+Q2il0DMphNnkD2mjQg3dfIxu9fSTHfy0/fcSFd8G75pPvV8t3dm9wNMRW5WCuDo5cd2Y1hqMp/+DpVzDq60t9/W15YoD9a9CZEpaZoVocVjDSB8DCbSz7IQcfRBy1wAej8mpgsS55Iy3iqxwIz0UGVh/Pn3OBNLaw=
